### ISSUE TITLE
--help or something similar

### ISSUE THREAD

**Issue by insanemal** [david0/ldapbrowse#4]
Not having help or even displaying usage when wrong flags are presented is, honestly, pretty user hostile.

**Comment by david0** [comment]
Good point. I hate the fact that getopt can not auto generate something. 
I added a simple usage if a wrong option is passed:
```./ldapbrowse -p 1234 -u               
./ldapbrowse: illegal option -- u
USAGE: ./ldapbrowse [-H ldapuri] [-D binddn] [-w passwd] [-h ldaphost] [-p ldapport] [-b searchbase] [-a {never|always|search|find}] [attributes...]
```

I was thinking of adding a manpage for complete documentation...
