### ISSUE TITLE
Unable to Delete

### ISSUE THREAD

**Issue by Justinzobel** [david0/ldapbrowse#5]
I have connected to the LDAP server with bindDN and password but D (capital d) using shift + d doesn't seem to do anything.

**Comment by Justinzobel** [comment]
Using latest git clone.

**Comment by david0** [comment]
Thanks for the hint, there is a bug in showing the delete message/dialog (do you really want to delete?) and also the error messages.

Workaround: If you press `y` it still will delete it. If its not deleting when you can try running `ldapdelete -h ...` and see what error messages are there.

**Comment by Justinzobel** [comment]
Ahh all good, I was just testing this out as a nice way of browsing our openldap server. I'll wait for a bugfix and try again, thanks!
